version: '2'
services:
  riemann:
    image: rlister/riemann:latest

  mongodb:
    image: mongo:latest

  postgres:
    image: postgres:latest

  app:
    image: lxclojure:latest
    command: /home/lxsameer/app/scripts/run.sh
    links:
      - postgres:postgres
      - riemann:riemann

    depends_on:
      - postgres
      - riemann

    volumes:
      - ./:/home/lxsameer/app
      - ./target:/home/lxsameer/app/target
