version: '2'
services:
  riemann:
    image: rlister/riemann:latest

  mongodb:
    image: mongo:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    image: lxclojure:latest
    command: /bin/bash
    tty: true
    environment:
      http_proxy: "http://172.18.0.1:8118"
      https_proxy: "http://172.18.0.1:8118"

    links:
      - postgres:postgres
      - riemann:riemann

    depends_on:
      - postgres
      - riemann

    volumes:
      - ./:/home/lxsameer/app
      - ./.m2:/home/lxsameer/.m2
