version: '2'
services:
  riemann:
    image: rlister/riemann:latest

  rethink:
    image: rethinkdb:latest

  app:
    image: lxclojure:latest
    command: /bin/bash
    tty: true
    environment:
      http_proxy: "http://172.18.0.1:8118"
      https_proxy: "http://172.18.0.1:8118"

    links:
      - rethink:rethink
      - riemann:riemann

    depends_on:
      - rethink
      - riemann

    volumes:
      - ./:/home/lxsameer/app
      - ./.m2:/home/lxsameer/.m2
