version: '2'
services:
  # riemann:
  #   image: rlister/riemann:latest

  rethink:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
  app:
    image: lxsameer/clojure:latest
    command: lein repl :headless
    environment:
      http_proxy: "http://172.18.0.1:8118"
      https_proxy: "http://172.18.0.1:8118"
      LEIN_REPL_PORT: 9182
      LEIN_REPL_HOST: '0.0.0.0'

    ports:
      - "127.0.0.1:9182:9182"

    links:
      - rethink:rethink
      #- riemann:riemann

    depends_on:
      - rethink
      #- riemann

    volumes:
      - ./:/home/lxsameer/app
      - ./.m2:/home/lxsameer/.m2
