version: '2'
services:
  # riemann:
  #   image: rlister/riemann:latest
  zookeeper:
    image: jplock/zookeeper:latest
    network_mode: 'host'

  mesos_master:
    image: lxsameer/mesos:0.28.2.2
    environment:
      MESOS_ZK: "zk://127.0.0.1:2181/mesos"
      MESOS_QUORUM: "1"
      # For production use relpicated_log
      MESSOS_REGISTRY: 'in_memory'
      MESOS_IP: '0.0.0.0'
      MESOS_WORK_DIR: '/var/lib/mesos'
      MESOS_LOG_DIR: '/var/log/mesos'

    network_mode: 'host'
    depends_on:
      - zookeeper


  mesos_slave:
    image: lxsameer/mesos:0.28.2.2
    depends_on:
      - mesos_master

    network_mode: 'host'
    environment:
      MESOS_HOSTNAME: 'slave_1'
      MESOS_MASTER: 'zk://127.0.0.1:2181/mesos'
      MESOS_LOG_DIR: '/var/log/mesos'
      MESOS_LOGGING_LEVEL: 'INFO'
      MESOS_WORK_DIR: '/var/lib/mesos'
      MESOS_SWITCH_USER: '0'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_SLAVE: 'true'
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/sys"
      - "/cgroup:/cgroup"
  marathon:
    image: mesoscloud/marathon:1.1.1-ubuntu-15.04
    network_mode: 'host'
    #command: marathon --master zk://127.0.0.1:2181/mesos zk://localhost:2181/marathon
    environment:
      MARATHON_ZK: 'zk://127.0.0.1:2181/marathon'
      MARATHON_MASTER: 'zk://127.0.0.1:2181/mesos'
      MARATHON_HOSTNAME: 'marathon'
      MARATHON_HTTPS_ADDRESS: '0.0.0.0'
      MARATHON_HTTP_ADDRESS: '0.0.0.0'
    depends_on:
      - mesos_master

  # kafka:
  #   image: ches/kafka:latest
  #   links:
  #     - zookeeper:zookeeper

  # rethink:
  #   image: rethinkdb:latest
  #   ports:
  #     - "8080:8080"

  # app:
  #   image: lxsameer/clojure:latest
  #   command: lein repl :headless
  #   environment:
  #     http_proxy: "http://172.18.0.1:8118"
  #     https_proxy: "http://172.18.0.1:8118"
  #     LEIN_REPL_PORT: 9182
  #     LEIN_REPL_HOST: '0.0.0.0'

  #   ports:
  #     - "127.0.0.1:9182:9182"

  #   links:
  #     - rethink:rethink
  #     #- riemann:riemann

  #   depends_on:
  #     - rethink
  #     #- riemann

  #   volumes:
  #     - ./:/home/lxsameer/app
  #     - ./.m2:/home/lxsameer/.m2
